# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/Backend_Test_Challenge

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
          
      # run tests!
      - run: mvn test
            
      - store_test_results: 
          path: target/surefire-reports
      
      - store_artifacts: 
          path: target/API-output.log
      - store_artifacts: 
          path: target/surefire-reports

workflows:
  version: 2
  RestAssuredTest:
    triggers: #Scheduled build
      - schedule:
          cron: "27 * * * *" 
          filters:
            branches:
              only:
                - master
    jobs:
      - build
